server:
  jasyptKey: dionysos-authorization

spring:
  redis:
    host: ENC(/QOaz1LAkTBggUDDlSybyz8zbuXq3Ukr)
    port: 6379
    password: ENC(7EOZn1pkXFXEzuY/jyCpI8xKZHcW2lOC)
    #개발/운영 따로 반영 필요
jasypt:
  encryptor:
    bean: jasyptStringEncryptor